### ISSUE TITLE
Can't Install on VPS Debian 12 kernel 5.4 .that say in photo.

### ISSUE THREAD

**Issue by lusoe302** [Ysurac/openmptcprouter#3266] opened 2024-04-12 05:04 UTC
## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: 
  - Country:

**Comment by Ysurac** [comment] 2024-04-12 05:44
Maybe a duplicate of https://github.com/Ysurac/openmptcprouter/issues/3265

**Closed by Ysurac** 2024-04-12 05:44 UTC
Labels: bug
