### ISSUE TITLE
Setup different vps ports

### ISSUE THREAD

**Issue by manueldev** [Ysurac/openmptcprouter#467] opened 2019-05-09 01:16 UTC
## Expected Behavior

My situation: I am trying to connect several geographically separated points (using adsl, hfc, 4g connections) to a dedicated server to access the internal network without interruptions. Actually I only need glorytun vpn but it escapes my technical knowledge how to do it on the outside and openmptcprouter brings everything ready with a friendly interface.

Is it possible to configure the VPS ports? I think that in this way I could use several VM instances of the VPS on the same ip (currently I have one running on virtualbox. I read that with docker containers the use of resources goes better but [I think there are no advances in that feature](https://github.com/Ysurac/docker-openmptcprouter-vps/issues/1)).

**Comment by Ysurac** [comment] 2019-05-09 06:35
Not supported for now.
Duplicate of https://github.com/Ysurac/openmptcprouter-vps/issues/6

**Closed by Ysurac** 2019-05-09 06:35 UTC
Labels: duplicate
