### ISSUE TITLE
opkg update fail 

### ISSUE THREAD

**Issue by lordmelathar** [Ysurac/openmptcprouter#2187] opened 2021-11-24 10:02 UTC
## Expected Behavior

opkg update work smooth

## Current Behavior

opkg fail to download packages from ssl sources

Collected errors:
 * opkg_download: Failed to download https://download.openmptcprouter.com/release/v0.58.5/rpi4/targets/bcm27xx/bcm2711/packages/Packages.gz, wget returned 5.
 * opkg_download: Failed to download https://download.openmptcprouter.com/release/v0.58.5/rpi4/packages/aarch64_cortex-a72/base/Packages.gz, wget returned 5.
 * opkg_download: Failed to download https://download.openmptcprouter.com/release/v0.58.5/rpi4/packages/aarch64_cortex-a72/luci/Packages.gz, wget returned 5.
 * opkg_download: Failed to download https://download.openmptcprouter.com/release/v0.58.5/rpi4/packages/aarch64_cortex-a72/openmptcprouter/Packages.gz, wget returned 5.
 * opkg_download: Failed to download https://download.openmptcprouter.com/release/v0.58.5/rpi4/packages/aarch64_cortex-a72/packages/Packages.gz, wget returned 5.

## Possible Solution

Install wget-ssl package

## Steps to Reproduce the Problem

  1. run opkg update

## Context (Environment)

openmptcprouter v0.58.5 r0+16336-b36068d35d

## Specifications

  - OpenMPTCProuter version: 0.58.5

**Comment by Ysurac** [comment] 2021-11-24 10:03
Duplicate of https://github.com/Ysurac/openmptcprouter/issues/2099

**Closed by Ysurac** 2021-11-24 10:03 UTC
Labels: bug
