### ISSUE TITLE
[OpenMPTCProuter 0.60 beta 2] nftable bug dnsmasq

### ISSUE THREAD

**Issue by Kalimeiro** [Ysurac/openmptcprouter#3174] opened 2024-02-18 13:52 UTC
## Specifications

  - OpenMPTCProuter version: 0.60 beta 2 snapshot 14/02/2024
  - OpenMPTCProuter VPS version: 0.1029-test
  - OpenMPTCProuter VPS provider: OVH
  - OpenMPTCProuter platform: x86_64
  - Country: FR

```
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:08 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dscp_cs2_6 Error: Could not resolve hostname: Name has no usable address
Feb 18 14:43:10 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:10 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:12 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:12 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:12 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:13 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:13 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:13 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:13 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dscp_cs2_6 Error: Could not resolve hostname: Name has no usable address
Feb 18 14:43:15 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:20 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:20 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:21 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_eth1_4 Error: No such file or directory
Feb 18 14:43:21 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:23 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:23 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:23 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:23 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:24 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:24 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:24 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:24 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:24 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:24 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:24 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:24 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:24 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:24 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:25 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:25 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:28 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:28 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:29 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:29 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:33 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:33 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:35 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:36 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:36 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:38 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:38 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:38 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:38 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:39 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:39 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:39 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:39 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:39 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:39 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:39 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:39 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:43:41 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dscp_cs4_6 Error: Could not resolve hostname: Name has no usable address
Feb 18 14:43:41 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dscp_cs2_6 Error: Could not resolve hostname: Name has no usable address
Feb 18 14:43:42 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dscp_cs4_6 Error: Could not resolve hostname: Name has no usable address
Feb 18 14:43:42 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dscp_cs4_6 Error: Could not resolve hostname: Name has no usable address
Feb 18 14:43:42 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dscp_cs4_6 Error: Could not resolve hostname: Name has no usable address
Feb 18 14:43:42 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dscp_cs4_6 Error: Could not resolve hostname: Name has no usable address
Feb 18 14:43:42 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dscp_cs4_6 Error: Could not resolve hostname: Name has no usable address
Feb 18 14:43:42 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dscp_cs4_6 Error: Could not resolve hostname: Name has no usable address
Feb 18 14:43:42 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dscp_cs4_6 Error: Could not resolve hostname: Name has no usable address
Feb 18 14:43:42 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dscp_cs4_6 Error: Could not resolve hostname: Name has no usable address
Feb 18 14:43:42 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dscp_cs4_6 Error: Could not resolve hostname: Name has no usable address
Feb 18 14:43:44 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:53 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:53 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:53 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:53 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:53 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:53 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:53 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:53 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:54 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:54 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:54 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:54 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:55 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:55 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:55 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:55 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:58 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:58 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:58 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:43:58 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:44:02 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:44:02 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:44:02 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:44:02 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:44:02 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:44:02 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:44:02 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:44:02 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:44:02 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:44:02 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:44:02 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:44:02 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:44:02 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:44:02 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:44:02 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:44:02 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:44:02 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:44:02 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:44:02 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:44:02 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
Feb 18 14:44:03 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:44:03 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:44:03 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:44:03 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_6 Error: No such file or directory
Feb 18 14:44:04 openmptcp-xxx daemon.err dnsmasq[1]: nftset inet fw4 omr_dst_bypass_all_4 Error: No such file or directory
```

**Comment by Ysurac** [comment] 2024-02-18 18:50
Duplicate of https://github.com/Ysurac/openmptcprouter/issues/3171

**Closed by Ysurac** 2024-02-18 18:50 UTC
Labels: bug

**Comment by Ysurac** [comment] 2024-02-19 19:11
It was an error when servers are disabled but rules enabled and init script of shadowsocks launched. It's fixed now.
What proxy are you using ?

**Comment by Ysurac** [comment] 2024-02-23 19:07
What is the result of ```uci show firewall.omr_dst_bypass_all_4``` and of ```nft list ruleset | grep omr_dst_bypass_all_4``` ?

**Comment by Ysurac** [comment] 2024-02-23 19:35
Strange, the nftables set is correctly present... There is no log about a firewall restart ?

nftset is the name of the variable used in dnsmasq config.
What do you as result of ```cat /tmp/etc/dnsmasq.conf.* | grep nftset``` ?

**Comment by Ysurac** [comment] 2024-02-24 08:18
All is ok here too.
Maybe when there is a firewall restart/reload. I will try to reproduce and check why it can restart.

**Comment by Ysurac** [comment] 2024-02-24 19:47
Should be better with last commit.
