### ISSUE TITLE
No token after upgrade openmptcprouter to 0.53.1

### ISSUE THREAD

**Issue by D4rk4** [Ysurac/openmptcprouter#765] opened 2019-12-25 18:44 UTC
**The error displayed on status page "Cant contact Server admin script (No Token)"** 

## Specifications

  - OpenMPTCProuter version: 0.53.1
  - OpenMPTCProuter VPS version: 0.1005
  - OpenMPTCProuter platform: X86_64

**Comment by Ysurac** [comment] 2019-12-25 18:45
Duplicate of #764

**Closed by Ysurac** 2019-12-25 18:45 UTC
Labels: duplicate
