### ISSUE TITLE
help I can't log into the router

### ISSUE THREAD

**Issue by ascomputer** [Ysurac/openmptcprouter#1485] opened 2020-12-30 10:50 UTC
after updating latest version when i log into router 192.168.100.1 it gives me this

/usr/lib/lua/luci/dispatcher.lua:427: /etc/config/luci seems to be corrupt, unable to find section 'main'

help me

**Comment by Ysurac** [comment] 2020-12-30 10:55
Duplicate of https://github.com/Ysurac/openmptcprouter/issues/1468

**Closed by Ysurac** 2020-12-30 10:55 UTC
Labels: help wanted
