### ISSUE TITLE
Small UI issue - auto refresh translation prevent to see tabs

### ISSUE THREAD

**Issue by Chatissimus** [Ysurac/openmptcprouter#945] opened 2020-03-31 17:53 UTC
## Expected Behavior

 tab well displayed

## Actual Behavior

tab overwritten by the header 

French : 
![firefox_YxAn7eyqxw](https://user-images.githubusercontent.com/62938061/78058520-b5bc8980-7388-11ea-996d-bb647174184a.png)

English :  
![firefox_kgSWip4hVC](https://user-images.githubusercontent.com/62938061/78058534-ba813d80-7388-11ea-8346-5497430d376d.png)

## Steps to Reproduce the Problem

  1. swith language to french
  2. open a tab with auto refresh

## Specifications

  - OpenMPTCProuter version: 0.54.7
  - OpenMPTCProuter VPS version: 0.1015
  - OpenMPTCProuter platform: RPI4

**Comment by Ysurac** [comment] 2020-03-31 18:00
Duplicate of https://github.com/Ysurac/openmptcprouter/issues/889
(already fixed in develop branch, so this will be for next release)

**Closed by Ysurac** 2020-03-31 18:00 UTC
Labels: duplicate
