### ISSUE TITLE
Multiple OMR clients on same vps

### ISSUE THREAD

**Issue by highfreq** [Ysurac/openmptcprouter#1952] opened 2021-07-13 06:02 UTC
## Expected Behavior
Is it possible to use multiple OMR on same VPS or is only one to one?
Thanks

**Comment by Ysurac** [comment] 2021-07-13 06:08
Duplicate of https://github.com/Ysurac/openmptcprouter/issues/1058
In short answer: no and this is not needed in most use case. Only advantage is when you want to do some clients to clients communications.

**Closed by Ysurac** 2021-07-13 06:08 UTC
Labels: duplicate, help wanted
