### ISSUE TITLE
Random redundancy on WAN On / Off

### ISSUE THREAD

**Issue by openaspace** [Ysurac/openmptcprouter#1293] opened 2020-10-09 15:27 UTC
## Expected Behavior
When a WAN go offline and come back online , the redundancy will restart on each wan device

## Current Behavior
I have 2 Lan WAN (physical ethernet devices) + 1 Wan using tethered phones.
When I start a new tcp connection the redundancy start correctly on all wan, 
but disconnecting and reconnecting 1 wan device the redundancy don't restart.
Also happen all the same, that with 2 wan on and 1 wan off, that disconnecting and reconnecting one of the 2 wan on, the 3rd with redundancy not started previously, start !

## Possible Solution
Possible routing problem at reconnection of a previous off wan device.

## Steps to Reproduce the Problem

  1. 3 WAN connected, tunnel working, redundancy working.
  2. disconnect and reconnect **WAN 1** and redundancy **don't start newly on WAN 1**
  3. I disconnect WAN 2 (redundancy on wan 1 remain off)
  4. I reconnect WAN 2 
  5. No redundancy restart on WAN 2
  6. but redundancy on WAN 1 start!
  7. Redundancy on wan 2 remain off.

## Context (Environment)
I use mptcp router in redundancy mode. 
I have'd the same problem previously, therefore i was started from new installation and 0 configuration
Also tried to change from laptop with lan  usb adapter to a dedicated dell server with 3 embed nic with the same problem, that replicate exactly

## Specifications

  - OpenMPTCProuter version: v0.55.3 r0+14198-da98603597
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter platform: AMD 64bit single core

![OpenMPTCProuter-Stato-LuCI (1)](https://user-images.githubusercontent.com/13104356/95601957-8c299c80-0a54-11eb-9417-51d60a83e7f6.png)

**Comment by Ysurac** [comment] 2020-10-09 15:32
Duplicate of https://github.com/Ysurac/openmptcprouter/issues/1271

**Closed by Ysurac** 2020-10-09 15:32 UTC
Labels: bug
