### ISSUE TITLE
Just checking if it is Possible to connect 2 devices with one server..?

### ISSUE THREAD

**Issue by iamdivyanshverma** [Ysurac/openmptcprouter#2438] opened 2022-07-26 13:16 UTC
## Specifications

  - OpenMPTCProuter version: 
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform:

**Comment by Ysurac** [comment] 2022-07-27 06:35
Duplicate of https://github.com/Ysurac/openmptcprouter/issues/1058
In short answer: no and this is not needed in most use case. Only advantage is when you want to do some clients to clients communications.

**Closed by Ysurac** 2022-07-27 06:35 UTC
Labels: help wanted

**Comment by squeaky-geek** [comment] 2022-12-05 09:06
i have done it, as of 12-5-2022 dual client to same vps is functioning...

**Comment by iamdivyanshverma** [comment] 2022-12-05 09:28
Hi @squeaky-geek ....
Both of your client device has different tunnel ip..?

**Comment by squeaky-geek** [comment] 2022-12-05 10:41
I didn't bother to check that, here is what I have:
Client 1: latest omr , [ server IP ] , omr server admin key. I checked the box under additional options " force retrieve all keys from server "

Client 2 : exact same config as " client 1 ". 

As far as I am aware, if there WERE an IP address conflict, neither client would be able to connect... I'll re do the double client setup and see if the ip's are different.  Side note: a webfig ( think Luci style ) for the server at least for stats would be awesome...

**Comment by iamdivyanshverma** [comment] 2022-12-05 11:09
@squeaky-geek thanks man..
Let me know if you get different ip for your device..!

**Comment by Ysurac** [comment] 2022-12-05 19:14
Glorytun doesn't allow multiple connections, so this can't work correctly this way.
You can also have multiples configuration conflicts.

**Comment by rdmitry0911** [comment] 2025-03-13 07:54
> Yes, confirmed not working :( I also would like this functionality...

Still not working, would like to make it work too
