### ISSUE TITLE
USB boot raspberrypi 4 

### ISSUE THREAD

**Issue by techdeisel** [Ysurac/openmptcprouter#1661] opened 2021-03-11 01:00 UTC
**Is your feature request related to a problem? Please describe.**
cant boot from usb 

**Describe the solution you'd like**
USB boot from flash drive or ssd

**Describe alternatives you've considered**

**Additional context**

**Comment by Ysurac** [comment] 2021-03-15 10:24
Duplicate of https://github.com/Ysurac/openmptcprouter/issues/1658

**Closed** 2021-03-15 10:24 UTC
Labels: duplicate, feature request
