### ISSUE TITLE
Kernel Panic at Kernel 6.1

### ISSUE THREAD

**Issue by moses2203** [Ysurac/openmptcprouter#3364] opened 2024-05-17 17:04 UTC
## Expected Behavior

Hello, 
I installed the x86_64 image on an Intel n100 system. The image with kernel 6.1 triggers a kernel panic. I then tested the image with the 5.9 kernel which then worked. Can you tell me what the problem is? I'm attaching a screenshot.

## Specifications

  - OpenMPTCProuter version: openmptcprouter-v0.60-6.1-r0+24843-acf40c022e-x86-64-generic-ext4-combined-efi.img.gz
  - OpenMPTCProuter VPS version: 
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: x86_64

![Screenshot_20240517_191043_Gallery](https://github.com/Ysurac/openmptcprouter/assets/170125256/8ae5e098-fb9d-4206-9e0f-341a00ac0252)
![Screenshot_20240517_184855_Gallery](https://github.com/Ysurac/openmptcprouter/assets/170125256/6986d423-759f-477b-a599-bfa67c0777f6)

**Comment by Ysurac** [comment] 2024-05-17 17:42
Duplicate of https://github.com/Ysurac/openmptcprouter/issues/3217

**Closed by Ysurac** 2024-05-17 17:42 UTC
Labels: help wanted
