### ISSUE TITLE
ERROR SERVER

### ISSUE THREAD

**Issue by sonnyxp2008** [Ysurac/openmptcprouter#2108] opened 2021-10-04 13:47 UTC
Resolving www.openmptcprouter.com (www.openmptcprouter.com)... 95.141.xxx
Connecting to www.openmptcprouter.com (www.openmptcprouter.com)|95.141.xxx5|:4                                                                                                                                                             43... connected.
ERROR: The certificate of ‘www.openmptcprouter.com’ is not trusted.
ERROR: The certificate of ‘www.openmptcprouter.com’ has expired.

**Comment by Ysurac** [comment] 2021-10-04 13:53
Duplicate of  #2105

**Closed** 2021-10-04 13:53 UTC
Labels: duplicate

**Comment by sonnyxp2008** [comment] 2021-10-04 14:00
keeps giving the same problem debian 10
