### ISSUE TITLE
Can I use two OpenMPTCProuter setups?

### ISSUE THREAD

**Issue by hairydogltd** [Ysurac/openmptcprouter#1642] opened 2021-03-02 12:49 UTC
I wonder if it is possible to have more than one OpenMPTCProuter setup connecting to the same VPS server?
This is so I can combine two 4G connections when away from home. I would want the home setup to keep running.

**Comment by Ysurac** [comment] 2021-03-02 12:59
Duplicate of #1058

**Closed by Ysurac** 2021-03-02 12:59 UTC
Labels: duplicate, question
