### ISSUE TITLE
OpenVpn cannot aggrate SRT UDP  by the latest snap shot

### ISSUE THREAD

**Issue by fareign** [Ysurac/openmptcprouter#3246] opened 2024-04-03 02:22 UTC
OpenVPN cannot aggrate UDP,I wizard settings ,reboot, it steel not work.
I change to glorytuntcp is OK.

## Specifications

  - OpenMPTCProuter version:snap 6.1
  - OpenMPTCProuter VPS version: 0.1029test
  - OpenMPTCProuter VPS provider:aliyun
  - OpenMPTCProuter platform: x86_64
  - Country:cn

**Comment by Ysurac** [comment] 2024-04-03 06:45
Duplicate of #3233 and #3227

**Closed by Ysurac** 2024-04-03 06:45 UTC
Labels: bug

**Comment by fareign** [comment] 2024-04-03 09:08
not the same problem
