### ISSUE TITLE
S98omr-bypass error on OMR 0.59.2 alpha bug 

### ISSUE THREAD

**Issue by Kalimeiro** [Ysurac/openmptcprouter#2836] opened 2023-04-29 18:17 UTC
## Specifications

    OpenMPTCProuter version: 0.59.2 ALPHA snap release 29/04/2023
    OpenMPTCProuter VPS version: 0.1029-test
    OpenMPTCProuter VPS provider: OVH
    OpenMPTCProuter platform: x86_64 and RPI4
    Country: FR

When start OMR i see a lot of unknown commands parsed to S98omr-bypass script on the system log :

Sat Apr 29 20:09:42 2023 user.notice omr-bypass: Starting OMR-ByPass...
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: Usage: uci [<options>] <command> [<arguments>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: Commands:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	batch
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	export     [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	import     [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	changes    [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	commit     [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	add        <config> <section-type>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	add_list   <config>.<section>.<option>=<string>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	del_list   <config>.<section>.<option>=<string>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	show       [<config>[.<section>[.<option>]]]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	get        <config>.<section>[.<option>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	set        <config>.<section>[.<option>]=<value>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	delete     <config>[.<section>[[.<option>][=<id>]]]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	rename     <config>.<section>[.<option>]=<name>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	revert     <config>[.<section>[.<option>]]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	reorder    <config>.<section>=<position>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: Options:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-c <path>  set the search path for config files (default: /etc/config)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-d <str>   set the delimiter for list values in uci show
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-f <file>  use <file> as input instead of stdin
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-m         when importing, merge data into an existing package
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-n         name unnamed sections on export (default)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-N         don't name unnamed sections
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-p <path>  add a search path for config change files
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-P <path>  add a search path for config change files and use as default
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-t <path>  set save path for config change files
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-q         quiet mode (don't print error messages)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-s         force strict mode (stop on parser errors, default)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-S         disable strict mode
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-X         do not use extended syntax on 'show'
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: Usage: uci [<options>] <command> [<arguments>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: Commands:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	batch
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	export     [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	import     [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	changes    [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	commit     [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	add        <config> <section-type>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	add_list   <config>.<section>.<option>=<string>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	del_list   <config>.<section>.<option>=<string>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	show       [<config>[.<section>[.<option>]]]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	get        <config>.<section>[.<option>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	set        <config>.<section>[.<option>]=<value>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	delete     <config>[.<section>[[.<option>][=<id>]]]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	rename     <config>.<section>[.<option>]=<name>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	revert     <config>[.<section>[.<option>]]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	reorder    <config>.<section>=<position>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: Options:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-c <path>  set the search path for config files (default: /etc/config)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-d <str>   set the delimiter for list values in uci show
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-f <file>  use <file> as input instead of stdin
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-m         when importing, merge data into an existing package
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-n         name unnamed sections on export (default)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-N         don't name unnamed sections
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-p <path>  add a search path for config change files
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-P <path>  add a search path for config change files and use as default
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-t <path>  set save path for config change files
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-q         quiet mode (don't print error messages)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-s         force strict mode (stop on parser errors, default)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-S         disable strict mode
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-X         do not use extended syntax on 'show'
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: Usage: uci [<options>] <command> [<arguments>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: Commands:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	batch
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	export     [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	import     [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	changes    [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	commit     [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	add        <config> <section-type>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	add_list   <config>.<section>.<option>=<string>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	del_list   <config>.<section>.<option>=<string>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	show       [<config>[.<section>[.<option>]]]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	get        <config>.<section>[.<option>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	set        <config>.<section>[.<option>]=<value>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	delete     <config>[.<section>[[.<option>][=<id>]]]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	rename     <config>.<section>[.<option>]=<name>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	revert     <config>[.<section>[.<option>]]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	reorder    <config>.<section>=<position>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: Options:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-c <path>  set the search path for config files (default: /etc/config)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-d <str>   set the delimiter for list values in uci show
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-f <file>  use <file> as input instead of stdin
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-m         when importing, merge data into an existing package
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-n         name unnamed sections on export (default)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-N         don't name unnamed sections
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-p <path>  add a search path for config change files
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-P <path>  add a search path for config change files and use as default
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-t <path>  set save path for config change files
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-q         quiet mode (don't print error messages)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-s         force strict mode (stop on parser errors, default)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-S         disable strict mode
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-X         do not use extended syntax on 'show'
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: Usage: uci [<options>] <command> [<arguments>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: Commands:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	batch
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	export     [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	import     [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	changes    [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	commit     [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	add        <config> <section-type>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	add_list   <config>.<section>.<option>=<string>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	del_list   <config>.<section>.<option>=<string>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	show       [<config>[.<section>[.<option>]]]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	get        <config>.<section>[.<option>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	set        <config>.<section>[.<option>]=<value>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	delete     <config>[.<section>[[.<option>][=<id>]]]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	rename     <config>.<section>[.<option>]=<name>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	revert     <config>[.<section>[.<option>]]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	reorder    <config>.<section>=<position>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: Options:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-c <path>  set the search path for config files (default: /etc/config)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-d <str>   set the delimiter for list values in uci show
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-f <file>  use <file> as input instead of stdin
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-m         when importing, merge data into an existing package
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-n         name unnamed sections on export (default)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-N         don't name unnamed sections
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-p <path>  add a search path for config change files
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-P <path>  add a search path for config change files and use as default
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-t <path>  set save path for config change files
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-q         quiet mode (don't print error messages)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-s         force strict mode (stop on parser errors, default)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-S         disable strict mode
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-X         do not use extended syntax on 'show'
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: Usage: uci [<options>] <command> [<arguments>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: Commands:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	batch
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	export     [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	import     [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	changes    [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	commit     [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	add        <config> <section-type>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	add_list   <config>.<section>.<option>=<string>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	del_list   <config>.<section>.<option>=<string>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	show       [<config>[.<section>[.<option>]]]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	get        <config>.<section>[.<option>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	set        <config>.<section>[.<option>]=<value>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	delete     <config>[.<section>[[.<option>][=<id>]]]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	rename     <config>.<section>[.<option>]=<name>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	revert     <config>[.<section>[.<option>]]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	reorder    <config>.<section>=<position>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: Options:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-c <path>  set the search path for config files (default: /etc/config)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-d <str>   set the delimiter for list values in uci show
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-f <file>  use <file> as input instead of stdin
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-m         when importing, merge data into an existing package
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-n         name unnamed sections on export (default)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-N         don't name unnamed sections
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-p <path>  add a search path for config change files
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-P <path>  add a search path for config change files and use as default
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-t <path>  set save path for config change files
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-q         quiet mode (don't print error messages)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-s         force strict mode (stop on parser errors, default)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-S         disable strict mode
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-X         do not use extended syntax on 'show'
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: Usage: uci [<options>] <command> [<arguments>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: Commands:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	batch
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	export     [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	import     [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	changes    [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	commit     [<config>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	add        <config> <section-type>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	add_list   <config>.<section>.<option>=<string>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	del_list   <config>.<section>.<option>=<string>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	show       [<config>[.<section>[.<option>]]]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	get        <config>.<section>[.<option>]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	set        <config>.<section>[.<option>]=<value>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	delete     <config>[.<section>[[.<option>][=<id>]]]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	rename     <config>.<section>[.<option>]=<name>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	revert     <config>[.<section>[.<option>]]
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	reorder    <config>.<section>=<position>
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: Options:
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-c <path>  set the search path for config files (default: /etc/config)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-d <str>   set the delimiter for list values in uci show
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-f <file>  use <file> as input instead of stdin
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-m         when importing, merge data into an existing package
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-n         name unnamed sections on export (default)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-N         don't name unnamed sections
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-p <path>  add a search path for config change files
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-P <path>  add a search path for config change files and use as default
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-t <path>  set save path for config change files
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-q         quiet mode (don't print error messages)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-s         force strict mode (stop on parser errors, default)
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-S         disable strict mode
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass: 	-X         do not use extended syntax on 'show'
Sat Apr 29 20:09:43 2023 daemon.notice procd: /etc/rc.d/S98omr-bypass:

**Comment by Ysurac** [comment] 2023-04-29 20:07
Duplicate of #2832

**Closed by Ysurac** 2023-04-29 20:07 UTC
Labels: bug
