### ISSUE TITLE
Difference between reboot from web page and command line

### ISSUE THREAD

**Issue by highfreq** [Ysurac/openmptcprouter#2167] opened 2021-11-09 07:14 UTC
If i reboot my raspberry OMR from webpage it always returns online with no probs. If i reboot it from ssh than when it comes up gives me connection refused when i try to login from webpage or ssh.
Connections are intended trough vps not local.
It looks like when i reboot it from command line it is not able to pass port configuration to server.

When it is locked from outside if i connect to its wifi and go into firewall-->port forwarding and do any slight modification and save it than it works again and let me in from thepublic ip again.
It really looks like port forwarding setup gets stuck when i reboot from command line.

**Comment by Ysurac** [comment] 2021-11-09 07:34
Please don't open multiples issue for same problem. And use template.
Duplicate of https://github.com/Ysurac/openmptcprouter/issues/2164

**Closed by Ysurac** 2021-11-09 07:34 UTC
Labels: help wanted

**Comment by highfreq** [comment] 2021-11-09 07:38
Sorry, i kind of narrowed down the problem so i tought of opening a new thread.
