### ISSUE TITLE
activating IPV6 adresse for server OMR router Side put the OMR VPS off

### ISSUE THREAD

**Issue by vinceducat** [Ysurac/openmptcprouter#3273] opened 2024-04-13 23:25 UTC
## Expected Behavior
configurer the ipv6 of the router omr router side ... 

## Current Behavior
doing that OMR VPS fall down :-(

need to contact my vps provider to restart i think
## Possible Solution
no idea :-)

## Steps to Reproduce the Problem

  1. put the ipv6 adresse of the server in the wizard for vps server
  2. save modifications
  3. omr vps stop to work

## Context (Environment)
putting ipv6 omr vps on omr router ..

## Specifications

  - OpenMPTCProuter version: 0.60 kernel 6.1
  - OpenMPTCProuter VPS version: 0.1030
  - OpenMPTCProuter VPS provider: Milkywan (debian 12 kernel 6.1 
  - OpenMPTCProuter platform:  x86_64
  - Country: France

**Comment by Ysurac** [comment] 2024-04-14 17:11
Duplicate of https://github.com/Ysurac/openmptcprouter/issues/3280

**Closed by Ysurac** 2024-04-14 17:11 UTC
Labels: bug
