### ISSUE TITLE
openvpn and mlvpn run failed on the lastest VPS. 

### ISSUE THREAD

**Issue by abilly007** [Ysurac/openmptcprouter#115] opened 2018-07-31 02:41 UTC
## Expected Behavior

  In English please.

## Steps to Reproduce the Problem

  1.when i install the shadowsocks and glorytun by the script debian9-x86_64.sh, they work well.
  2.and then i change the script debian9-x86.sh by set MLVPN=${MLVPN:-yes} and OPENVPN=${OPENVPN:-yes}, and run it to install. i found there a bit problem :
     1) in the script debian9-x86_64.sh the omr-6in4 change into omr-service ,and omr-6in4-service
          change into omr-6in4.service.in form last version, but in the script debian9-x86_64-mlvpn didnot   change them ;
     2) the bellow command return  error ,is the filename change on the server ?
  wget -O /lib/systemd/network/openvpn.network http://www.openmptcprouter.com/server/openvpn.network 
  3. after i fix the two bug, and install is ok. but when i run them in serice mode, they failed all.
   root@instance-ai0i4ljl:~# systemctl status openvpn-server@tun0.service
● openvpn-server@tun0.service - OpenVPN service for tun0
   Loaded: loaded (/lib/systemd/system/openvpn-server@.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:openvpn(8)
           https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
           https://community.openvpn.net/openvpn/wiki/HOWTO
root@instance-ai0i4ljl:~# 
root@instance-ai0i4ljl:~# systemctl status openvpn-server@tun0
● openvpn-server@tun0.service - OpenVPN service for tun0
   Loaded: loaded (/lib/systemd/system/openvpn-server@.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:openvpn(8)
           https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
           https://community.openvpn.net/openvpn/wiki/HOWTO
root@instance-ai0i4ljl:~# systemctl status mlvpn@mlvpn0.service
● mlvpn@mlvpn0.service - MLVPN connection to mlvpn0
   Loaded: loaded (/lib/systemd/system/mlvpn@.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2018-07-31 10:02:33 CST; 2min 39s ago
  Process: 749 ExecStart=/usr/local/sbin/mlvpn --config /etc/mlvpn/mlvpn0.conf --user mlvpn (code=exited, status=1/FAILURE)
 Main PID: 749 (code=exited, status=1/FAILURE)

Jul 31 10:02:33 instance-ai0i4ljl systemd[1]: mlvpn@mlvpn0.service: Unit entered failed state.
Jul 31 10:02:33 instance-ai0i4ljl systemd[1]: mlvpn@mlvpn0.service: Failed with result 'exit-code'.
Jul 31 10:02:33 instance-ai0i4ljl systemd[1]: mlvpn@mlvpn0.service: Service hold-off time over, scheduling restart.
Jul 31 10:02:33 instance-ai0i4ljl systemd[1]: Stopped MLVPN connection to mlvpn0.
Jul 31 10:02:33 instance-ai0i4ljl systemd[1]: mlvpn@mlvpn0.service: Start request repeated too quickly.
Jul 31 10:02:33 instance-ai0i4ljl systemd[1]: Failed to start MLVPN connection to mlvpn0.
Jul 31 10:02:33 instance-ai0i4ljl systemd[1]: mlvpn@mlvpn0.service: Unit entered failed state.
Jul 31 10:02:33 instance-ai0i4ljl systemd[1]: mlvpn@mlvpn0.service: Failed with result 'exit-code'.
root@instance-ai0i4ljl:~# 

can you help me take a look?thanks.

## Specifications

  - OpenMPTCProuter version: (Last is not a version)
  - OpenMPTCProuter VPS version: (Last is not a version) V0.39
  - OpenMPTCProuter platform: (RPI2/RPI3/x86/x86_64)

**Comment by Ysurac** [comment] 2018-07-31 07:50
1) Fixed
2) The file exist, what is the error ?
3) 
* What do you have in ```journalctl -xte``` ?
* What is the result of ```/usr/local/sbin/mlvpn --config /etc/mlvpn/mlvpn0.conf --user mlvpn``` ?
* What is the result of ```/usr/sbin/openvpn --config /etc/openvpn/server/tun0.conf``` ?

**Comment by abilly007** [comment] 2018-07-31 09:53
1. i get it.
2.
![x lv8xjcf zvgssv 7trbh](https://user-images.githubusercontent.com/37547039/43452662-7ea1387c-94a7-11e8-909b-0472d2c1e9ea.png)

 
3.
![i pq fgel1x0l2m r36f tx](https://user-images.githubusercontent.com/37547039/43452368-d23c1f52-94a6-11e8-8e2e-e49a25913c0a.png)

**Comment by Ysurac** [comment] 2018-07-31 10:19
2. Strange, my server connection closed by client. What is the result if you try https instead of http ?
3. 
* For MLVPN, ```/var/run/mlvpn``` exist ? Seems to be cleared at reboot. In latest version I use /var/opt/mlvpn.
* For OpenVPN, I'm able to reproduce the issue, I will fix it ASAP.

**Comment by abilly007** [comment] 2018-07-31 10:58
2. use https instead of http that is ok.
3. there didnot exist /var/run/mlvpn and /var/opt/mlvpn.

**Comment by Ysurac** [comment] 2018-07-31 12:46
All should be fixed in latest OpenMPTCProuter VPS script.

**Comment by abilly007** [comment] 2018-08-01 06:48
hi,Ysurac, i update the VPS script to lastest, and running is ok. but there still a few problems have bothered me. 
1.first , i use shadowsock and glorytunVPN tcp or glorytunVPN udp ,they all work well,and i can see the tunnel is established,i can ping success from each other.
2. but,when i disable  shadowsock , I can't access any web site through the browser,is should be all the  traffic go throught by VPN when the shadowsock is disable(how it can do this i'm not very clear.) ,they seems didnot work?
3. when i change the default VPN from glorytunTCP to MLVPN, the tunnel interface name change into mlvpn0 but didnot have a client ip,so i think the vpn tunnel didnot established.

**Comment by Ysurac** [comment] 2018-08-01 07:30
1. ok
2. Strange, working for me. How to you try to disable ShadowSocks ? What OpenMPTCProuter version are you using ?
3. Did you set MLVPN key ? It get IP from DHCP when MLVPN can connect.

**Comment by abilly007** [comment] 2018-08-01 07:36
2. by command line : /etc/init.dadowsocks-libev stop ,the openMPTCProuter is v0,29 rpi2  download from your web.
3.yes, ss,glorytun mlvpn all the key had set.

**Comment by Ysurac** [comment] 2018-08-01 07:49
2. Update to v0.29.1 and use interface to disable it :)
3. Same, try v0.29.1. If no change try to reboot VPS.

**Comment by abilly007** [comment] 2018-08-01 09:17
2.it's already v0.29.1 of openMPTCProuter.use interface to disable shadowsocks? there are several local instances,e.g. ss_local ,ss_redir1,ss_redir2,ss_tunnel.etc,and a remote server, and a redir rules .i have to disable all of them beside the remote server?that seems is not a convenient way.
3.the VPS is the lastest v0.40 and had been reboot.

**Comment by Ysurac** [comment] 2018-08-01 10:45
2. You only need to check the **Disable** case on **Remote Servers** tab in ShadowSocks interface. You can also remove key in OpenMPTCProuter wizard.
3. Strange. MLVPN is running on the VPS ? Can you check if the key in ```/etc/mlvpn/mlvpn0.conf``` is the same as what you set to be sure ?

**Comment by abilly007** [comment] 2018-08-02 02:04
2.I get it.But after I disabled shadowsocks from the interface like you say, I still couldn't access any website through the browser, but my QQ (an instant messaging APP) could log in and communicate. 

3. I had check the key of mlvpn config of the both router and VPS ，the are the same. but it still don't work .

**Closed** 2018-12-26 14:40 UTC
