### ISSUE TITLE
Need Info

### ISSUE THREAD

**Issue by ssdeol84** [Ysurac/openmptcprouter#1830] opened 2021-05-14 04:23 UTC
Dear sir

I've got new router TP-Link TL-WR841N/ND v9

I'm entering the information of my Shadowsocks server in the router.

It is having three tabs in ss-tunnel module to enter Shadowsocks information of my server.

1st tab is Local instances
In that I've two information

1) ss_redir.hi

Which is asking me the information :

server:
Local address: 0.0.0.0
Local port: 1100
Verbose:0
Ipv6_first: 0
fast_open:0
no_delay:0
Mode: tcp_and_udp
Timeout:1000
mptcp:1

2) ss_tunnel.dns

server:sss0
Local_Port:5353
Tunnel_address:8.8.8.8:53
Mode: tcp_and_udp

![IMG_20210514_094910.jpg](https://user-images.githubusercontent.com/69002306/118220587-a7043980-b499-11eb-80da-0e1f2e635e03.jpg)

2nd Tab is Remote server

![IMG_20210514_094956.jpg](https://user-images.githubusercontent.com/69002306/118220630-c307db00-b499-11eb-81c5-60124908cc01.jpg)

3rd tab is Redir Rules

I've created the server from your script.

Can you help me out how I can get connected with my server through this router what information we need to put in these tabs?

Or do you have firmware for this device ?

**Comment by Ysurac** [comment] 2021-05-14 05:33
You don't need to open multiples issues: This will not work. OpenMPTCProuter shadowsocks is patched and, for example, use only key and no password.
Duplicate of https://github.com/Ysurac/openmptcprouter/issues/1825

**Closed by Ysurac** 2021-05-14 05:33 UTC
