### ISSUE TITLE
Unable to keep DHCPv6 server enabled in LAN interface

### ISSUE THREAD

**Issue by DeeJayMX** [Ysurac/openmptcprouter#1003] opened 2020-05-04 14:13 UTC
## Expected Behavior
No change when the rooter reboot

## Current Behavior
When OMR reboot, the settings in LAN interface for DHCP service in IPV6 goes to disable

## Possible Solution
really don't know
if I reactivate the option, the DHCP Server goes on and work until next reboot.

## Steps to Reproduce the Problem
Juste activate the DHCPv6 on LAN and restart from GUI
![image](https://user-images.githubusercontent.com/36418772/80975224-17599300-8e22-11ea-9ca4-a6cc745c8a0f.png)

## Context (Environment)
1 Lan on eth0
3 Wan on VLAN with eth0.11 0.12 0.13
I want to get IPv6 IPs for my LAN

## Specifications

  - OpenMPTCProuter version: v0.54.7 r0+12509-04a21c26a0
  - OpenMPTCProuter VPS version: 0.1015 4.19.104-mptcp
  - OpenMPTCProuter platform: RPi4B 4Go

and thanks Ysurac for the great great piece of gold you made 💯

**Comment by Ysurac** [comment] 2020-05-04 14:16
Duplicate of https://github.com/Ysurac/openmptcprouter/issues/971
This will be fixed in next release.

**Closed** 2020-05-04 14:16 UTC
Labels: duplicate
