### ISSUE TITLE
omr-admin.py[27869]: ERROR:    [Errno -9] Address family for hostname not supported

### ISSUE THREAD

**Issue by iPowerTech** [Ysurac/openmptcprouter#3680] opened 2024-11-23 19:11 UTC
## Expected Behavior
Server Admin Script Works correctly 

## Current Behavior
Serverl Log.
omr-admin.py[27869]: ERROR:    [Errno -9] Address family for hostname not supported

## Steps to Reproduce the Problem
install ORM v.0.1031 on Ubuntu 20.04 Kermel 5.4
using install script 
wget -O - https://www.openmptcprouter.com/server/ubuntu20.04-x86_64.sh  | KERNEL="5.4" sh
try to start ORM-Admin 

## Specifications
  - OpenMPTCProuter version:  openmptcprouter v0.61-5.4 r0+16862-170d9e447d
  - OpenMPTCProuter VPS version:   Ubuntu20.04  Kernel 5.4  OMR v.0.1031
  - OpenMPTCProuter VPS provider: ServerPlan
  - OpenMPTCProuter platform: x86_64
  - Country: IT
  - Python 3.8.10

**Comment by Ysurac** [comment] 2024-11-23 20:39
Duplicate of #3679

**Closed by Ysurac** 2024-11-23 20:39 UTC
Labels: bug
