### ISSUE TITLE
[OpenMPTCProuter 0.60 beta 2] nftable bug omr-6in4

### ISSUE THREAD

**Issue by Kalimeiro** [Ysurac/openmptcprouter#3172] opened 2024-02-18 13:49 UTC
## Specifications

  - OpenMPTCProuter version: 0.60 beta 2 snapshot 14/02/2024
  - OpenMPTCProuter VPS version: 0.1029-test
  - OpenMPTCProuter VPS provider: OVH
  - OpenMPTCProuter platform: x86_64
  - Country: FR

```
Feb 18 13:42:46 openmptcp-xxx user.notice omr-6in4: Enable IPv6
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: xargs: resolveip: exited with status 255; aborting
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: In file included from /tmp/ssrules.nft.chk:1:17-43:
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: /tmp/ssrules.nft:38:3-3: Error: syntax error, unexpected -, expecting comma or '}'
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: 		-4,
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: 		^
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: In file included from /tmp/ssrules.nft.chk:1:17-43:
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: /tmp/ssrules.nft:39:3-3: Error: syntax error, unexpected '['
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: 		[-t,
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: 		^
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: In file included from /tmp/ssrules.nft.chk:1:17-43:
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: /tmp/ssrules.nft:40:10-10: Error: syntax error, unexpected ']', expecting string
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: 		timeout],
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: 		       ^
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: In file included from /tmp/ssrules.nft.chk:1:17-43:
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: /tmp/ssrules.nft:41:3-10: Error: syntax error, unexpected string
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: 		hostname,
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: 		^^^^^^^^
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: In file included from /tmp/ssrules.nft.chk:1:17-43:
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: /tmp/ssrules.nft:42:3-11: Error: syntax error, unexpected string
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: 		resolveip,
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: 		^^^^^^^^^
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: In file included from /tmp/ssrules.nft.chk:1:17-43:
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: /tmp/ssrules.nft:43:3-3: Error: syntax error, unexpected -
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: 		-6,
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: 		^
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: In file included from /tmp/ssrules.nft.chk:1:17-43:
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: /tmp/ssrules.nft:44:3-3: Error: syntax error, unexpected '['
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: 		[-t,
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: 		^
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: In file included from /tmp/ssrules.nft.chk:1:17-43:
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: /tmp/ssrules.nft:45:10-10: Error: syntax error, unexpected ']', expecting string
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: 		timeout],
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: 		       ^
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: In file included from /tmp/ssrules.nft.chk:1:17-43:
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: /tmp/ssrules.nft:46:3-10: Error: syntax error, unexpected string
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: 		hostname,
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: 		^^^^^^^^
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: In file included from /tmp/ssrules.nft.chk:1:17-43:
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: /tmp/ssrules.nft:47:3-11: Error: syntax error, unexpected string
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: 		resolveip,
Feb 18 13:42:46 openmptcp-xxx daemon.notice procd: /etc/rc.d/S99omr-6in4: 		^^^^^^^^^

```

**Comment by Ysurac** [comment] 2024-02-18 18:48
Duplicate of https://github.com/Ysurac/openmptcprouter/issues/3173

**Closed by Ysurac** 2024-02-18 18:48 UTC
Labels: bug
