### ISSUE TITLE
Close all port and IP except one

### ISSUE THREAD

**Issue by rsajadi63** [Ysurac/openmptcprouter#1727] opened 2021-04-07 09:15 UTC
I need to only one port (1935) on Server 
And only server’s IP .I will close all port and all IP on openmptcprouter So that clients can not connect to the Internet or any other external ip only and only to the server’s IP and only the 1935 port

**Comment by Ysurac** [comment] 2021-04-07 09:18
stop opening issue for same problem.
Duplicate of #1717

**Closed by Ysurac** 2021-04-07 09:18 UTC
Labels: help wanted
