### ISSUE TITLE
Does Golang needed to be installed for unsupported platform image create?

### ISSUE THREAD

**Issue by atyouspace** [Ysurac/openmptcprouter#2336] opened 2022-04-20 07:59 UTC
Hi @Ysurac 

During this period of time, I have sent three related posts asking for help, and I have also researched a lot. The problem became clearer.
I would like to know, is Golang installation package necessary when building an unsupported platform image?

Because from ERRORs, I found that I can not download from "[https://proxy.golang.org]".
I'm guessing that this problem may have caused a series of problems.

Best regards

**Comment by Ysurac** [comment] 2022-04-20 17:58
Duplicate of #2335

**Closed by Ysurac** 2022-04-20 17:58 UTC
Labels: help wanted
